@startuml

left to right direction

actor Пользователь as User #blue
actor System #red

User --> (Изучить образовательный контент)
(Изучить образовательный контент) <-- System
(Изучить образовательный контент) <|-left- (Пройти викторину на тему космоса)
(Изучить образовательный контент) <|-left- (Изучить глоссарий космических терминов)
(Изучить образовательный контент) <|-- (Просмотреть статьи на тему космоса)

User --> (Узнать условия для наблюдения небесных явлений)
(Узнать условия для наблюдения небесных явлений) <-- System
(Получить уведомление о времени и месте для наблюдения) .> (Узнать условия для наблюдения небесных явлений) : extend

User --> (Узнать космическую погоду)
(Узнать космическую погоду) <-- System
(Узнать космическую погоду) <|-- (Узнать уровень солнечной активности - УФ-индекс)
(Узнать космическую погоду) <|-left- (Узнать функциональность GPS)
(Узнать космическую погоду) <|-right- (Узнать геомагнитную активность - магнитные бури)

User --> (Просмотреть космическую картинку дня)
(Просмотреть космическую картинку дня) <-- System

User --> (Редактировать образовательный контент)
(Редактировать образовательный контент) <-- System
(Редактировать образовательный контент) <|-left- (Добавить термин в глоссарий)
(Редактировать образовательный контент) <|-right- (Добавить статью)
(Редактировать образовательный контент) <|-- (Добавить вопросы в викторину)


(Добавить в закладки) ..> (Просмотреть статьи на тему космоса) : extend
(Добавить в закладки) .> (Изучить глоссарий космических терминов) : extend
(Добавить в закладки) .left.> (Пройти викторину на тему космоса) : extend

@enduml
